### ISSUE TITLE
WebGL build fails in Unity 2021

### ISSUE THREAD

**Issue by andreydobrikov** [mirage-xyz/mirage-unity-sdk#34]
Currently if you build the SDK in 2020 in WebGL everything works as expected. However if you upgrade to Unity 2021.3 LTS WebGL build fails to build during linking. The exact issue seems to be related to WebGL assembly and throw a signature mismatch error. @sidorovkirill @Vukiz, have you tried building the SDK using 2021 and have you seen those issues before?

**Comment by Vukiz** [comment]
Hello @andreydobrikov !
Can you please verify that you are using the correct version? 
We've moved the development from this repo to https://github.com/Ankr-network/game-unity-sdk

**Comment by andreydobrikov** [comment]
Yes, I'm using https://github.com/Ankr-network/game-unity-sdk, but there is no way for me to submit an issue in that fork.

**Comment by Vukiz** [comment]
> Yes, I'm using https://github.com/Ankr-network/game-unity-sdk, but there is no way for me to submit an issue in that fork.

fixed that and added issues page, sorry for that:)

**Comment by Vukiz** [comment]
> @Vukiz below is the log from Unity:
> 
> Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output: wasm-ld: error: function signature mismatch: GetChainId
> 
> > > > defined as (i32) -> void in C:\Users\Andrey\AppData\Local\Temp\tmpu4zyliotGameAssembly.a(j263_rSDK.WebGL.o)
> > > > defined as (i32, i32, i32) -> void in C:\Users\Andrey\AppData\Local\Temp\tmpu4zyliotGameAssembly.a(uuln_reum.Unity.o)
> > > > emcc2: error: 'E:/Unity/2021.3.7f1/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/llvm\wasm-ld.exe -o Library/Bee/artifacts/WebGL/build/debug_WebGL_wasm/build.wasm C:\Users\Andrey\AppData\Local\Temp\tmpu4zyliotGameAssembly.a C:\Users\Andrey\AppData\Local\Temp\tmp1o9w4wqhWebGLSupport_AccessibilityModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpavcfaugaWebGLSupport_AIModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp48jr4tlwWebGLSupport_AndroidJNIModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp8ef0oowvWebGLSupport_AnimationModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpimqd3ea4WebGLSupport_AssetBundleModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp2upx2gx9WebGLSupport_AudioModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmppn2adbs9WebGLSupport_ClothModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpx788gb6fWebGLSupport_CoreModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpnw2satzdWebGLSupport_CrashReportingModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpo35ya0cyWebGLSupport_DirectorModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpvexqodeqWebGLSupport_DSPGraphModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpquven60zWebGLSupport_GameCenterModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpn0q0rtq2WebGLSupport_GIModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpnqg0qli8WebGLSupport_GridModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp9caz79q5WebGLSupport_HotReloadModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp4o45eabvWebGLSupport_ImageConversionModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpw_woch9yWebGLSupport_IMGUIModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp4jtu28njWebGLSupport_InputLegacyModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpm7ido0ahWebGLSupport_InputModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp58nevcflWebGLSupport_JSONSerializeModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmprwg7hrz_WebGLSupport_LocalizationModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpg2zfall1WebGLSupport_ParticleSystemModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpzd3w1ip9WebGLSupport_PerformanceReportingModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp125fv4jyWebGLSupport_Physics2DModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp8hjgtzsmWebGLSupport_PhysicsModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpz3ooy63mWebGLSupport_ProfilerModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp2qxlkv4gWebGLSupport_RuntimeInitializeOnLoadManagerInitializerModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmptfotmcslWebGLSupport_ScreenCaptureModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp0uedz97vWebGLSupport_SharedInternalsModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp9loix4oaWebGLSupport_SpriteMaskModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpilkhr83_WebGLSupport_SpriteShapeModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpt0sgt4sxWebGLSupport_StreamingModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpvqomnbqrWebGLSupport_SubstanceModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp5cy6obveWebGLSupport_SubsystemsModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpzymhfhy2WebGLSupport_TerrainModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp7kdklvihWebGLSupport_TerrainPhysicsModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpdzqe85kyWebGLSupport_TextCoreFontEngineModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp1u7h8x_dWebGLSupport_TextCoreTextEngineModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpcl9db06lWebGLSupport_TextRenderingModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmprwed7213WebGLSupport_TilemapModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpy_4dvlw4WebGLSupport_TLSModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp_tgxpvb_WebGLSupport_UIElementsModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp_pqduzf8WebGLSupport_UIElementsNativeModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpjdxh3udyWebGLSupport_UIModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpykj423hzWebGLSupport_UmbraModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpaw9o_qcjWebGLSupport_UNETModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpkotysy3iWebGLSupport_UnityAnalyticsModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpuc1lvx13WebGLSupport_UnityConnectModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp_8gop707WebGLSupport_UnityCurlModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpp7d506s6WebGLSupport_UnityTestProtocolModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmprebffxk3WebGLSupport_UnityWebRequestAssetBundleModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpgz1o_hw4WebGLSupport_UnityWebRequestAudioModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpa1yup0_5WebGLSupport_UnityWebRequestModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpqprfwcc4WebGLSupport_UnityWebRequestTextureModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpmigwl_i0WebGLSupport_UnityWebRequestWWWModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpald2u48qWebGLSupport_VehiclesModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp68ke53l5WebGLSupport_VFXModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpw6e1plxlWebGLSupport_VideoModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpajpm7xrmWebGLSupport_VRModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp3w7xf8qzWebGLSupport_WebGLModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmpka0vkx_oWebGLSupport_WindModule_Dynamic.a C:\Users\Andrey\AppData\Local\Temp\tmp7wjk5ap_WebGLSupport_XRModule_Dynamic.a -LE:\Unity\2021.3.7f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot\lib\wasm32-emscripten E:\Unity\2021.3.7f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot\lib\wasm32-emscripten\libgl-webgl2-full_es3.a E:\Unity\2021.3.7f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot\lib\wasm32-emscripten\libal.a E:\Unity\2021.3.7f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot\lib\wasm32-emscripten\libhtml5.a E:\Unity\2021.3.7f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot\lib\wasm32-emscripten\libc.a E:\Unity\2021.3.7f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot\lib\wasm32-emscripten\libcompiler_rt.a E:\Unity\2021.3.7f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot\lib\wasm32-emscripten\libc++.a E:\Unity\2021.3.7f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot\lib\wasm32-emscripten\libc++abi.a E:\Unity\2021.3.7f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot\lib\wasm32-emscripten\libdlmalloc.a E:\Unity\2021.3.7f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot\lib\wasm32-emscripten\libc_rt_wasm.a E:\Unity\2021.3.7f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot\lib\wasm32-emscripten\libsockets.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined --export main --export emscripten_stack_get_end --export emscripten_stack_get_free --export emscripten_stack_init --export __cxa_demangle --export stackSave --export stackRestore --export stackAlloc --export __wasm_call_ctors --export fflush --export __errno_location --export malloc --export free --export __cxa_is_pointer_type --export __cxa_can_catch --export setThrew --export ntohs --export strlen --export htonl --export htons --export memset --export _get_tzname --export _get_daylight --export _get_timezone --export memalign --export emscripten_main_thread_process_queued_calls --export emscripten_webgl_make_context_current --export emscripten_webgl_get_current_context --export-table --export __start_em_asm --export __stop_em_asm -z stack-size=5242880 --initial-memory=33554432 --no-entry --max-memory=2147483648 --global-base=1024' failed (1)
> > > > UnityEditor.BuildPlayerWindow:BuildPlayerAndRun ()

taking a look

**Comment by andreydobrikov** [comment]
Replacing Pointer__stringify() with UTF8ToString in Web3gl.jslib and other jslibs for 2021.2 onwards seem to do the track as Unity recommends [here](https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html)

**Comment by Vukiz** [comment]
Thanks we will try to make an update for that

**Comment by andreydobrikov** [comment]
Also, need to update WebSocket.jslib to the latest that does the same as above according [to this PR](https://github.com/endel/NativeWebSocket/pull/54).

**Comment by sidorovkirill** [comment]
Hi @andreydobrikov. We are working on that issue. Fixed part that you describeed, but after that got another issue that probably goes from emscripten and specific for Unity 2021. Added comments for all forums related to this issue:
https://github.com/emscripten-core/emscripten/issues/17610
https://forum.unity.com/threads/webgl-build-error-unity2021-3-6.1320369/

**Comment by Vukiz** [comment]
Closing this issue as we've done what is possible from our side, the rest is unity
